// <auto-generated />
using GestionEmpleados.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionEmpleados.Migrations
{
    [DbContext(typeof(EmpleadosDbContext))]
    [Migration("20210921230413_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestionEmpleados.Models.Empleados", b =>
                {
                    b.Property<int>("CodEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("varchar (12)");

                    b.Property<string>("primerApellido")
                        .IsRequired()
                        .HasColumnType("varchar (150)");

                    b.Property<string>("primerNombre")
                        .IsRequired()
                        .HasColumnType("varchar (150)");

                    b.Property<string>("segundoApellido")
                        .IsRequired()
                        .HasColumnType("varchar (150)");

                    b.Property<string>("segundoNomre")
                        .IsRequired()
                        .HasColumnType("varchar (150)");

                    b.HasKey("CodEmpleado");

                    b.ToTable("Empleados");
                });
#pragma warning restore 612, 618
        }
    }
}
